version: "3.9"
services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: gim-backend-mysql
    ports:
      - '${MYSQL_FORWARD_DB_PORT}:3306'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
volumes:
  mysql:
    driver: local